/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.papenhagen.salestax.test;

/**
 *
 * @author jay
 */
public class Stub {

    public String getValidXMLRPC() {
        return "<?xml version=\"1.0\"?>\n"
                + "<methodResponse>\n"
                + "<params>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>UstId_1</string></value>\n"
                + "<value><string></string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>ErrorCode</string></value>\n"
                + "<value><string>215</string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>UstId_2</string></value>\n"
                + "<value><string>DE813890706</string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Druck</string></value>\n"
                + "<value><string>nein</string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Erg_PLZ</string></value>\n"
                + "<value><string></string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Ort</string></value>\n"
                + "<value><string></string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Datum</string></value>\n"
                + "<value><string>30.11.2018</string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>PLZ</string></value>\n"
                + "<value><string></string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Erg_Ort</string></value>\n"
                + "<value><string></string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Uhrzeit</string></value>\n"
                + "<value><string>09:40:26</string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Erg_Name</string></value>\n"
                + "<value><string></string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Gueltig_ab</string></value>\n"
                + "<value><string></string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Gueltig_bis</string></value>\n"
                + "<value><string></string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Strasse</string></value>\n"
                + "<value><string></string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Firmenname</string></value>\n"
                + "<value><string></string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "<param>\n"
                + "<value><array><data>\n"
                + "<value><string>Erg_Str</string></value>\n"
                + "<value><string></string></value>\n"
                + "</data></array></value>\n"
                + "</param>\n"
                + "</params>\n"
                + "</methodResponse>";
    }

}
